name: publish to nuget

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: False
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ReleaseChecker.GitHub/ReleaseChecker.GitHub.csproj --no-restore --configuration Release
    - name: Test
      run: dotnet test ReleaseChecker.GitHub/ReleaseChecker.GitHub.csproj --no-build --configuration Release --verbosity normal
    - name: Pack
      run: dotnet pack ReleaseChecker.GitHub/ReleaseChecker.GitHub.csproj --no-build --configuration Release -o __out
    - name: Push
      run: dotnet nuget push "./__out/*.nupkg" --source https://www.nuget.org --no-symbols --api-key ${{secrets.NUGET_API_KEY}}
